services:
  database:
    image: postgres
    container_name: dohackme_db
    restart: no
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  storage:
    image: minio/minio
    container_name: dohackme_storage
    restart: no
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data/storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server data --console-address ":9001"