name: Build and Push Live Image

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Azure
        uses: docker/login-action@v3
        with:
          registry: dohackme.azurecr.io
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./docker/production/Dockerfile
          push: true
          tags: dohackme.azurecr.io/dohack.me/dohack.me:beta
          secrets: |
            "NEXT_PUBLIC_BACKEND_HOST=${{ secrets.NEXT_PUBLIC_BACKEND_HOST }}"
            "NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}"
            "NEXT_PUBLIC_POSTHOG_HOST=${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}"
            "BACKEND_URL=${{ secrets.BACKEND_URL }}"
            "BACKEND_SECRET_KEY=${{ secrets.BACKEND_SECRET_KEY }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "DIRECT_URL=${{ secrets.DIRECT_URL }}"
            "AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }}"
            "AUTH_URL=${{ secrets.AUTH_URL }}"
            "AUTH_SECRET=${{ secrets.AUTH_SECRET }}"
            "AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }}"
            "AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }}"
            "AUTH_DISCORD_ID=${{ secrets.AUTH_DISCORD_ID }}"
            "AUTH_DISCORD_SECRET=${{ secrets.AUTH_DISCORD_SECRET }}"
            "AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}"
            "AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}"
            "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}"
            "S3_REGION=${{ secrets.S3_REGION }}"
            "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}"
            "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}"
            "S3_BUCKET=${{ secrets.S3_BUCKET }}"